### PR TITLE
Support PolkaGate Snap

### PR DESCRIPTION
**Pull request by AMIRKHANEF**
This PR introduces changes necessary to support PolkaGate Snap within the project.

Please note that this pull request must be merged after the initial PR, which adds the PolkaGate Snap logo, has been successfully merged.

Please take a look at issue #4349 carefully for further details and context.

Thank you for reviewing and considering this PR. Your feedback is appreciated!

Close: #4349

### CODE REVIEW

**Comment by AMIRKHANEF** [comment]
[@2nthony](https://github.com/2nthony)
Hi, I just pushed another commit to the repo. It seems one of your commits may have been lost in the process.

**Comment by 2nthony** [comment]
> [@2nthony](https://github.com/2nthony) Hi, I just pushed another commit to the repo. It seems one of your commits may have been lost in the process.

i pushed the commit is just for update icons.

**Comment by AMIRKHANEF** [comment]
> > [@2nthony](https://github.com/2nthony) Hi, I just pushed another commit to the repo. It seems one of your commits may have been lost in the process.
> 
> i pushed the commit is just for update icons.

I see, but unfortunately, it is not included in this PR because I pushed a commit after your commit.

**Comment by 2nthony** [comment]
if my browser have installed metamask, but `polkagate snap` not installed, then I clicked the `polkagate snap` button, it shows a error toast like below. So, we need to check both `metamask` and `polkagate snap` are installed to enable the button.

- [ ] Is there anyway to check the snap installed or not?

image

**Comment by 2nthony** [comment]
@AMIRKHANEF but first, merge this pr please https://github.com/AMIRKHANEF/subsquare/pull/1

**Comment by AMIRKHANEF** [comment]
> @AMIRKHANEF but first, merge this pr please [AMIRKHANEF#1](https://github.com/AMIRKHANEF/subsquare/pull/1)

Done

**Comment by AMIRKHANEF** [comment]
> if my browser have installed metamask, but `polkagate snap` not installed, then I clicked the `polkagate snap` button, it shows a error toast like below. So, we need to check both `metamask` and `polkagate snap` are installed to enable the button.
> 
> * [ ]  Is there anyway to check the snap installed or not?
> 
> image

If MetaMask is installed on your browser but the PolkaGate Snap is not, it will not cause an error. Instead, a MetaMask popup will appear, prompting you to install the Snap.

Regarding the scenario you provided in the screenshot, it seems that the Snap was disabled manually. The alert popup from Subsquare is correctly indicating this issue to the user.

To answer your question, yes, there is a way to check if the Snap is installed and whether it is enabled.

**Comment by 2nthony** [comment]
yes, I disable the snap manually because we want to cover more user cases.

would you mind to modify the code to check the Snap if installed? the `polkagate snap` button enable condition should be `metamask` and the `Snap` both installed and enabled.

**Comment by AMIRKHANEF** [comment]
Hi, @2nthony 
As discussed, we've investigated the feasibility of verifying Snap's installation and activation status within MetaMask. We discussed with MetaMask team regarding the API and according to their guidance, the DApp must already be connected to Snap for these checks to be effective, which makes it useless.

Therefore, it's crucial to note that disabling the button under other conditions isn't advisable. Since Snap functions as an extension of MetaMask, having MetaMask installed alone is sufficient to enable the button and facilitate communication with the DApp.

As seen in the **[STAKING DASHBOARD](https://staking.polkadot.cloud/)**, having MetaMask installed is a prerequisite for interacting with Snap.

Furthermore, to optimize user experience and accommodate those who may not wish to use or install Snap, I've updated the code so that the connection is established only when users explicitly intend to engage with Snap by clicking the button.

**When MetaMask isn't installed, the PolkaGate Snap button is disabled:**
image

**When MetaMask isn't installed, but the PolkaGate Snap is not installed, the button is enabled:**
image

**When Snap is not installed, clicking the button will easily install Snap and display the account:**
image

**When Snap is disabled, an alert popup will display stating 'The Snap is disabled to the user.:**
image

**Pull request merged**
