### PR TITLE
fix nested/multi-level delegations bug

### PR DESCRIPTION
**Pull request by gabrieljaegerde**
Currently nested delegations are ignored in your implementation.

Let's take Kusama Ref 234 as an example:

On ref expiry wallet `GFTBZ1p9UFfn662hdbE84R9FFSkW1wHqyV8N2t27gW1fh8U` was delegating to `FnqFKGD4vy3P7S111itFG4Y8g8cf5RcCnL3QGTzbNWzePyn`. `FnqFKGD4vy3P7S111itFG4Y8g8cf5RcCnL3QGTzbNWzePyn` in turn was delegating to `HqRcfhH8VXMhuCk5JXe28WMgDDuW9MVDVNofe1nnTcefVZn`.

So when `HqRcfhH8VXMhuCk5JXe28WMgDDuW9MVDVNofe1nnTcefVZn`, delegated votes should be added for both `GFTBZ1p9UFfn662hdbE84R9FFSkW1wHqyV8N2t27gW1fh8U` and `FnqFKGD4vy3P7S111itFG4Y8g8cf5RcCnL3QGTzbNWzePyn`.

With this PR, a delegated entry for `FnqFKGD4vy3P7S111itFG4Y8g8cf5RcCnL3QGTzbNWzePyn` would first be added to the `votes` array. Where previously there was no entry available in the `directVotes` array for this wallet (since it also a delegated vote), there is one available now. When we process the delegation of `GFTBZ1p9UFfn662hdbE84R9FFSkW1wHqyV8N2t27gW1fh8U` then, we will find an entry for `FnqFKGD4vy3P7S111itFG4Y8g8cf5RcCnL3QGTzbNWzePyn` in the `votes` array and this delegation will be added too.

### CODE REVIEW

**Comment by wliyongfeng** [comment]
Hi @gabrieljaegerde , thanks for this PR, actually I took the code from @polkadot/api. But yeah I have found this bug and created a issue for @polkadot/api [here](https://github.com/polkadot-js/api/issues/5344), waiting for Jaco's confirmation.

My plan was to change `toDelegator.account` to `toDelegator.delegating.target` in following code, so `GF...` will use the vote of `Hq...`. 
```javascript
 const to = directVotes.find(
      ({ account }) =>
        account === (toDelegator ? toDelegator.account : target.toString())
);
```

But your code looks cool too and I'll merge your PR if I won't get Jaco's reply in 2 days.

**Comment by gabrieljaegerde** [comment]
Yes I noticed that your code is based on the api-derive package. Note that you did deviate from it with the `newVotes` array. The [api-derive logic](https://github.com/polkadot-js/api/blob/9b3258a65a0ebc369dd8c3fe90e4d57579832fe5/packages/api-derive/src/democracy/referendumsInfo.ts#L90) is the same as my fix where the delegated votes are being pushed to the `votes` array.

**Comment by wliyongfeng** [comment]
Wmm..., yes, you're right and I'll merge your PR.

**Comment by gabrieljaegerde** [comment]
Exactly. It will only work if the delegations in storage are ordered by delegation level in the way you described. Since this is also the code in the api-derive package, I would assume that it does indeed work that way. Would be good to double check though.

**Comment by wliyongfeng** [comment]
@gabrieljaegerde I think we all including polkadot.js made a mistake about nested/multi-level delegations. Kusama democracy doesn't support nested delegation from [referendum #43](https://kusama.subsquare.io/democracy/referendum/43). Check my [new script](https://github.com/opensquare-network/play-dot/blob/main/src/ksm/democracy/statistics/voting.js) to verify.

**Comment by gabrieljaegerde** [comment]
First of all thanks for sharing!

That is very interesting indeed. Definitely has to be incorporated into delegation UIs as right now nested delegations are permitted without warning but just simply not actually considered in the votes?

**Comment by wliyongfeng** [comment]
> just simply not actually considered in the votes?

@gabrieljaegerde Sure, only one level delegation is taken into the final calculation.

**Pull request merged**
